# Device Configuration
platformName=Android
deviceName=Android
automationName=UiAutomator2
appPackage=com.aistudio.foodshare.kbyqwe
appActivity=com.example.MainActivity
# For real devices, appPath is usually not required if the app is already installed,
# but can be used for auto-installation.
appPath=../app/build/outputs/apk/debug/app-debug.apk
udid=13869325160018C

# Appium Server
appiumServerUrl=http://127.0.0.1:4723

# Framework Settings
explicitWait=10
screenshotOnFailure=true
retryCount=1

# Test Data
excelPath=./excel/FoodShareAI_Appium_Test_Report.xlsx
logLevel=INFO
